### ISSUE TITLE
参数配置里in-ip无法配置

### ISSUE THREAD

**Issue by hua0424** [lbl8603/VntApp#4]
windows版本的客户端，在in-ip一栏，无论配置什么都提示错误，比如填192.168.0.1/24，提示：Exception 格式错误：192.168.0.1/24

**Comment by lbl8603** [comment]
输入框上面有示例，格式是 192.168.1.0/24,10.26.0.xx

**Comment by hua0424** [comment]
明白了，后面那个是目标网络的虚拟IP
